name: AMD64 Build
on: [push, pull_request]

jobs:
  windows_debug:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.7.0
        with:
          arch: x86
#          arch: x64
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Get processor arch
        run: echo "PROCESSOR_ARCH=$Env:PROCESSOR_ARCHITECTURE" | out-file -FilePath $Env:GITHUB_ENV -Encoding utf-8 -append

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
#      - name: Get Submodule Info
#        id: get-submodule-info
#        run: git ls-tree -r HEAD:3rdparty > ${{github.workspace}}/submodule_info
      - name: Cache 3rdparty builds
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/3rdparty/bin
            ${{github.workspace}}/build/3rdparty/lib
            ${{github.workspace}}/build/3rdparty/include
          key: ${{ runner.os }}-${{env.BUILD_TYPE}}-${{ hashFiles('submodule_info') }}

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ${{github.workspace}} -GNinja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Upload windows build
        uses: actions/upload-artifact@v2
        with:
          name: windows_debug_build
          path: |
            ${{github.workspace}}/build/bin/*
            !${{github.workspace}}/build/bin/*.pdb
      - name: Upload windows pdbs
        uses: actions/upload-artifact@v2
        with:
          name: windows_debug_pdbs
          path: |
            ${{github.workspace}}/build/bin/*.pdb


  windows_release:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.7.0
        with:
          arch: x86
#          arch: x64
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Get processor arch
        run: echo "PROCESSOR_ARCH=$Env:PROCESSOR_ARCHITECTURE" | out-file -FilePath $Env:GITHUB_ENV -Encoding utf-8 -append

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

#      - name: Get Submodule Info
#        id: get-submodule-info
#        run: git ls-tree -r HEAD:3rdparty > ${{github.workspace}}/submodule_info

      - name: Cache 3rdparty builds
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/3rdparty/bin
            ${{github.workspace}}/build/3rdparty/lib
            ${{github.workspace}}/build/3rdparty/include
          key: ${{ runner.os }}-${{env.BUILD_TYPE}}-${{ hashFiles('submodule_info') }}

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ${{github.workspace}} -GNinja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Upload windows build
        uses: actions/upload-artifact@v2
        with:
          name: windows_release_build
          path: |
            ${{github.workspace}}/build/bin/*
            !${{github.workspace}}/build/bin/*.lib
            !${{github.workspace}}/build/bin/*.pdb
      - name: Upload windows pdbs
        uses: actions/upload-artifact@v2
        with:
          name: windows_release_pdbs
          path: |
            ${{github.workspace}}/build/bin/*.pdb

  deploy:
    runs-on: ubuntu-latest
    needs: [ windows_release ]
    if: ${{ github.ref == 'refs/heads/tags' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Release Changelog Builder
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.0.0
        with:
          ignorePreReleases: true
          outputFile: ${{github.workspace}}/build/bin/changelog.txt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download windows build
        id: build_download
        uses: actions/download-artifact@v2.0.10
        with:
          name: windows_release_build

      - name: Release
        uses: ncipollo/release-action@v1.8.6
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          body: ${{steps.build_changelog.outputs.changelog}}
          commit: ${{ github.sha }}
          tag: v1.1.6.${{ github.run_number }}
          artifacts: ${{steps.build_download.outputs.download-path}}
          token: ${{ secrets.GITHUB_TOKEN }}

